data_file : data/data_xdsin_v2.txt # data/data_xdsin.txt ; data/data_xdsin_v2.txt ; data/data_xdlinear_full.txt
name : xdsin_v2 # xdsin ; xdsin_v2 ; xdlinear
model_pth : 00499.pth

system : sin # sin ; linear
eps : -inf

test : traj # traj ; accuracy
recursive : False
datatype : train # train ; val ; out ; in

obs : 3
preds : 1
hid_size : 8
layers : 1
cpu : False
verbose : False
max_epoch : 200
batch_size : 64
resue_train : False
save_step : 1

color : True

tlim : 50
nb_t : 1001
freq : 20
version : 2
dt : 2e-2
xlim : 3
plotlim : 3
lim0 : 2
lim1 : -2
lim2 : 0
acc : False
rotation : False

typeplot : save # save ; sigma
prefix : kernel_sin # kernel ; kernel_sin ; kernel_linear
sigma_file : data/sigmas_v2.pickle # data/sigmas.pickle ; data/sigmas_v2.pickle

dx : 1e-2
n1 : 61
n2 : 21
n3 : 51
gentype : plot # plot ; write

